---
title: "Generate PDF reports in LaTeX"
author: "Alberto Sanchez Rodelgo"
date: "2/11/2017"
output: html_document
---

Basic instructions on how to generate 2 pager PDF reports based on TCdata360 data. 

# Pre-requisites:

- Install the R packages listed in: **global_utils.R** plus **jsonlite** to process the TCdata360's API responses.
- TexLive installation (To be able to knit LaTeX code into PDF): <https://www.tug.org/texlive/quickinstall.html>

# Setup

1. This is meant to be run on a local environment, for now. So download this project and change accordingly all local paths in:

- **Writer_Report_data.R**
- **Report_Generator.R**
- **datapull_TCdata360.R**

2. The **templates** folder contains the custom report for instance, Entrepreneurship. Ideally you don't need to change anything outside of this **templates** folder. The parameter **input_reportID** defines what report you are working with. To edit an existing report or to create a new one, you must create 4 files within the templates folder:

  - **input_reportID_charts.R** calls to functions in helper_functions.R (charts, tables, etc.)
  - **input_reportID_DataDescription.csv** tell the report what indicators, units, sections, sources you will use. In more detail:

    * **Section**: Main topics within the report
    * **Subsection**: group tag indicators. Example: Use the same name for indicators you want to appear in the same chart/table. 
    * **Subsection2**: in case indicators are used in more than 1 place. In case indicators are used in 3 places, then a new column would need to be added (Subsection3), although I'm not sure this will work without further changes.
    * **tcdata360_id**: TCdata360 indicator ID per the API.
    * **Source_Name**: Name of data source to appear on report footnotes. Ex: WDI 
    * **Source_Link**: URL pointing to data source (as hyperlink to Source_Name)
  
    The rest of the columns should be self explanatory

  - **input_reportID_ReportConfiguration.csv** configuration file needed for the overall attributes of each report. Includes font color and header background color. The latter is constraint to the available images in www. Files: **header_background_[hexacolor].png**

  - **input_reportID_PDF_LaTeX.Rnw** layout of the report. Here you will layout the elements you described on **_charts.R** 

If you get lost please take a look at the 2 examples built in the project right now (Entrepreneurship and Tourism). This should help.

# Steps to generate PDF reports:

1. Run **Writer_Report_data.R** to pull and store the data from TCdata360's API. Important: If you change the downloaded data file location, it is usually a good practice to keep it outside the project directory (especially if you keep versions on Github, large files will make it crash)

2. The program is prepared to ingest data from other sources as well, you will have to define it in a similar way as in **Entrepreneurship_extraData.R**

3. Update the List topics on global_utils.R:
topics <- c("Entrepreneurship","Tourism",**"my_new_report"**)

4. Launch the shiny app and generate your desired report.

Note: In order to generate report for all countries in one go you can use a loop in **Report_Generator.R**


